export const RECEIVE_LOCATIONS = "RECEIVE_LOCATIONS";
export const APPEND_LIST = "APPEND_LIST";
export const SET_CURRENT_PLACE_NAME = "SET_CURRENT_PLACE_NAME";
export const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES";
export const REMOVE_FROM_FAVOURITES = "REMOVE_FROM_FAVOURITES";