export const GET_LOCATIONS = "GET_LOCATIONS";
export const RECEIVE_LOCATIONS = "RECEIVE_LOCATIONS";
export const APPEND_LIST = "APPEND_LIST";
export const SET_CURRENT_PLACE_NAME = "SET_CURRENT_PLACE_NAME";