const initialState = [
    {
        "id": 0,
        "bathroom_number": "",
        "bedroom_number": 5,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/5_bedroom_terraced_house_for_sale_109243771882962474.jpg",
        "img_width": 400,
        "keywords": "Terraced, Kitchen, Basement, Parking",
        "latitude": 53.8028,
        "lister_name": "Moores",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109243771882962474/title/5/1-1?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.56305,
        "price": 400000,
        "price_currency": "£",
        "price_formatted": "£400,000",
        "price_high": 400000,
        "price_low": 400000,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "Large period family terrace house on the fringe of the city centre,...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/5_bedroom_terraced_house_for_sale_109243771882962474.jpg",
        "thumb_width": 80,
        "title": "Victoria Terrace, Woodhouse, Leeds 3",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    },
    {
        "id": 1,
        "bathroom_number": "",
        "bedroom_number": 5,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/5_bedroom_detached_house_for_sale_109473089103357143.jpg",
        "img_width": 400,
        "keywords": "Detached, Garden, En suite, No Chain, Conservatory, Double Bedroom, Garage, Kitchen, Cul-de-Sac, Gas Central Heating",
        "latitude": 53.7783,
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109473089103357143/title/5/1-2?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.6034,
        "price": 359995,
        "price_currency": "£",
        "price_formatted": "£359,995",
        "price_high": 359995,
        "price_low": 359995,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "Five bedroom detached corner plot downstairs wc conservatory garage...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/5_bedroom_detached_house_for_sale_109473089103357143.jpg",
        "thumb_width": 80,
        "title": "Tingle View, Farnley, Leeds, West Yorkhsire, LS12",
        "updated_in_days": 2,
        "updated_in_days_formatted": "first seen 2 days ago"
    },
    {
        "id": 2,
        "bathroom_number": 2,
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/2_bedroom_house_for_sale_109466418649609668.jpg",
        "img_width": 400,
        "keywords": "Garden, Double Bedroom, Kitchen",
        "latitude": 53.8119,
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109466418649609668/title/5/1-3?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.58068,
        "price": 160000,
        "price_currency": "£",
        "price_formatted": "£160,000",
        "price_high": 160000,
        "price_low": 160000,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "Briefly comprising of; gated entrance to front garden, large living...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/2_bedroom_house_for_sale_109466418649609668.jpg",
        "thumb_width": 80,
        "title": "Beechwood Terrace, Burley , Leeds",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    },
    {
        "id": 3,
        "bathr3oom_number": "",
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/2_bedroom_flat_for_sale_109466418164383146.jpg",
        "img_width": 400,
        "keywords": "",
        "latitude": 53.7968,
        "lister_name": "Jll",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109466418164383146/title/5/1-4?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.55127,
        "price": 299950,
        "price_currency": "£",
        "price_formatted": "£299,950",
        "price_high": 299950,
        "price_low": 299950,
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "Bespoke two bedroom duplex apartment situated in the heart of ls1 w...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/2_bedroom_flat_for_sale_109466418164383146.jpg",
        "thumb_width": 80,
        "title": "The Old Cloth Warehouse, 3 York Place, Leeds, West Yorks, LS1",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    },
    {   "id": 4,
        "bathroom_number": "",
        "bedroom_number": 4,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/4_bedroom_semi_detached_house_for_sale_109405033702680890.jpg",
        "img_width": 400,
        "keywords": "Garden, Semi-Detached, En suite, Fireplace, Hot tub, Kitchen, Modern, Parking, Reception",
        "latitude": 53.839718,
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109405033702680890/title/5/1-5?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.5434254,
        "price": 299999,
        "price_currency": "£",
        "price_formatted": "£299,999",
        "price_high": 299999,
        "price_low": 299999,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "Kitchen high-specification kitchen benefiting from monochrome decor...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/4_bedroom_semi_detached_house_for_sale_109405033702680890.jpg",
        "thumb_width": 80,
        "title": "King Lane, Leeds, LS17 - Fireplace",
        "updated_in_days": 2,
        "updated_in_days_formatted": "first seen 2 days ago"
    },
    {   "id": 5,
        "bathroom_number": "",
        "bedroom_number": 3,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/3_bedroom_terraced_house_for_sale_109287058598185354.jpg",
        "img_width": 400,
        "keywords": "En suite, Terraced",
        "latitude": 53.8114,
        "lister_name": "Moores",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109287058598185354/title/5/1-6?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.58416,
        "price": 200000,
        "price_currency": "£",
        "price_formatted": "£200,000",
        "price_high": 200000,
        "price_low": 200000,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "Superb investment opportunity 3 bedrooms all en suite/private bathr...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/3_bedroom_terraced_house_for_sale_109287058598185354.jpg",
        "thumb_width": 80,
        "title": "Talbot Mount, Burley, Leeds 4",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    },
    {   "id": 6,
        "bathroom_number": "",
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/2_bedroom_apartment_for_sale_109466414385973500.jpg",
        "img_width": 400,
        "keywords": "Modern",
        "latitude": 53.7987,
        "lister_name": "Linley & Simpson",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109466414385973500/title/5/1-7?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.59182,
        "price": 99950,
        "price_currency": "£",
        "price_formatted": "£99,950",
        "price_high": 99950,
        "price_low": 99950,
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "A modern two bedroom duplex apartment situated to the west of the c...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/2_bedroom_apartment_for_sale_109466414385973500.jpg",
        "thumb_width": 80,
        "title": "WINKER GREEN LODGE, ARMLEY, LEEDS, LS12",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    },
    {   "id": 7,
        "bathroom_number": "",
        "bedroom_number": 3,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/3_bedroom_terraced_house_for_sale_109466418553045069.jpg",
        "img_width": 400,
        "keywords": "Terraced, Kitchen",
        "latitude": 53.7883,
        "lister_name": "Manning",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109466418553045069/title/5/1-8?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.58381,
        "price": 134995,
        "price_currency": "£",
        "price_formatted": "£134,995",
        "price_high": 134995,
        "price_low": 134995,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "Well-presented end town house situated in this residential location...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/3_bedroom_terraced_house_for_sale_109466418553045069.jpg",
        "thumb_width": 80,
        "title": "Highfield Crescent, Leeds, West Yorkshire",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    },
{       "id": 8,
        "bathroom_number": "",
        "bedroom_number": 1,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/1_bedroom_apartment_for_sale_109466419881985644.jpg",
        "img_width": 400,
        "keywords": "",
        "latitude": 53.790615,
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109466419881985644/title/5/1-9?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.525947,
        "price": 95000,
        "price_currency": "£",
        "price_formatted": "£95,000",
        "price_high": 95000,
        "price_low": 95000,
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "Reduced for quick sale 1 bedroom apartment in the echo central deve...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/1_bedroom_apartment_for_sale_109466419881985644.jpg",
        "thumb_width": 80,
        "title": "Echo Central, Leeds, LS9",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen over a month ago"
    },
    {   "id": 9,
        "bathroom_number": "",
        "bedroom_number": 1,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/1_bedroom_house_for_sale_109466416731336522.jpg",
        "img_width": 400,
        "keywords": "En suite, Furnished, Double Bedroom, Kitchen",
        "latitude": 53.793,
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109466416731336522/title/5/1-10?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.60836,
        "price": 85000,
        "price_currency": "£",
        "price_formatted": "£85,000",
        "price_high": 85000,
        "price_low": 85000,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "One bedroom apartment in this development. Recently renovated and f...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/1_bedroom_house_for_sale_109466416731336522.jpg",
        "thumb_width": 80,
        "title": "Swallow Hill, 353 Tong Road, Leeds",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    },
    {   "id": 10,
        "bathroom_number": "",
        "bedroom_number": 3,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/3_bedroom_terraced_house_for_sale_109466411762573673.jpg",
        "img_width": 400,
        "keywords": "Terraced, Double Bedroom, Kitchen",
        "latitude": 53.8241,
        "lister_name": "Linley & Simpson",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109466411762573673/title/5/1-11?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.53693,
        "price": 260000,
        "price_currency": "£",
        "price_formatted": "£260,000",
        "price_high": 260000,
        "price_low": 260000,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "Extended three bedroom end terrace located in a and sought after lo...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/3_bedroom_terraced_house_for_sale_109466411762573673.jpg",
        "thumb_width": 80,
        "title": "ST MARTINS ROAD, CHAPEL ALLERTON, LEEDS,LS7",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    },
    {   "id": 11,
        "bathroom_number": "",
        "bedroom_number": 4,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/4_bedroom_townhouse_for_sale_109466417589061468.jpg",
        "img_width": 400,
        "keywords": "Garden, En suite, Balcony, Garage, Kitchen, Modern",
        "latitude": 53.8297,
        "lister_name": "Manning",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109466417589061468/title/5/1-12?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.59006,
        "price": 340000,
        "price_currency": "£",
        "price_formatted": "£340,000",
        "price_high": 340000,
        "price_low": 340000,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "Ly presented throughout is this , four bedroom modern town house. L...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/4_bedroom_townhouse_for_sale_109466417589061468.jpg",
        "thumb_width": 80,
        "title": "Thornbury Avenue, Leeds, West Yorkshire",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    },
    {   "id": 12,
        "bathroom_number": "",
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/2_bedroom_semi_detached_house_for_sale_109466415279659938.jpg",
        "img_width": 400,
        "keywords": "Semi-Detached, Kitchen",
        "latitude": 53.8068,
        "lister_name": "Manning",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109466415279659938/title/5/1-13?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.60957,
        "price": 124995,
        "price_currency": "£",
        "price_formatted": "£124,995",
        "price_high": 124995,
        "price_low": 124995,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "Well-presented two bedroom semi-detached home, situated in the resi...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/2_bedroom_semi_detached_house_for_sale_109466415279659938.jpg",
        "thumb_width": 80,
        "title": "Wensleydale Avenue, Leeds",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    },
    {   "id": 13,
        "bathroom_number": "",
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/2_bedroom_apartment_for_sale_109460226291122182.jpg",
        "img_width": 400,
        "keywords": "Shared Garden, No Chain, Double Bedroom, Kitchen, Parking",
        "latitude": 53.8302,
        "lister_name": "Manning",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109460226291122182/title/5/1-14?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.60496,
        "price": 119995,
        "price_currency": "£",
        "price_formatted": "£119,995",
        "price_high": 119995,
        "price_low": 119995,
        "property_type": "flat",
        "size": 0,
        "size_type": "net",
        "summary": "No forward chain. Apartment set in location. Two double bedrooms. L...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/2_bedroom_apartment_for_sale_109460226291122182.jpg",
        "thumb_width": 80,
        "title": "Westbury Gardens, 129 Spen Lane, West Park, Leeds",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    },
    {   "id": 14,
        "bathroom_number": "",
        "bedroom_number": 3,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/3_bedroom_semi_detached_house_for_sale_109466415421441923.jpg",
        "img_width": 400,
        "keywords": "Garden, Semi-Detached, Kitchen",
        "latitude": 53.8342,
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109466415421441923/title/5/1-15?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.56534,
        "price": 289950,
        "price_currency": "£",
        "price_formatted": "£289,950",
        "price_high": 289950,
        "price_low": 289950,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "A skilfully extended semi detached family home, providing bright an...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/3_bedroom_semi_detached_house_for_sale_109466415421441923.jpg",
        "thumb_width": 80,
        "title": "Church Lane, Leeds LS6 - Garden",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    },
    {   "id": 15,
        "bathroom_number": "",
        "bedroom_number": 4,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/4_bedroom_detached_house_for_sale_109262330038655984.jpg",
        "img_width": 400,
        "keywords": "Detached, Garden, Kitchen, Reception",
        "latitude": 53.7919,
        "lister_name": "Manning",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109262330038655984/title/5/1-16?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.6166,
        "price": 279995,
        "price_currency": "£",
        "price_formatted": "£279,995",
        "price_high": 279995,
        "price_low": 279995,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "Ly presented, traditional double fronted detached family home. Read...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/4_bedroom_detached_house_for_sale_109262330038655984.jpg",
        "thumb_width": 80,
        "title": "Ring Road, Farnley, Leeds, West Yorkshire",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    },
    {   "id": 16,
        "bathroom_number": 2,
        "bedroom_number": 2,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/2_bedroom_house_for_sale_109466415959145070.jpg",
        "img_width": 400,
        "keywords": "",
        "latitude": 53.8299,
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109466415959145070/title/5/1-17?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.59203,
        "price": 215000,
        "price_currency": "£",
        "price_formatted": "£215,000",
        "price_high": 215000,
        "price_low": 215000,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "Newly renovated two bedroom apartment to let. This two bed two bath...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/2_bedroom_house_for_sale_109466415959145070.jpg",
        "thumb_width": 80,
        "title": "Carisbrooke Road, Headingley, Leeds",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    },
    {   "id": 17,
        "bathroom_number": "",
        "bedroom_number": 3,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/3_bedroom_semi_detached_house_for_sale_109466413737493541.jpg",
        "img_width": 400,
        "keywords": "Garden, Semi-Detached, No Chain",
        "latitude": 53.8181,
        "lister_name": "Manning",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109466413737493541/title/5/1-18?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.50897,
        "price": 184950,
        "price_currency": "£",
        "price_formatted": "£184,950",
        "price_high": 184950,
        "price_low": 184950,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "This semi-detached with well laid out accommodation and good size r...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/3_bedroom_semi_detached_house_for_sale_109466413737493541.jpg",
        "thumb_width": 80,
        "title": "Easterly Crescent, Leeds, West Yorkshire",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    },
    {   "id": 18,
        "bathroom_number": "",
        "bedroom_number": 3,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/3_bedroom_townhouse_for_sale_109460224256128945.jpg",
        "img_width": 400,
        "keywords": "Detached, Garden, Needs Modernisation, Detached Garage, Kitchen",
        "latitude": 53.7858,
        "lister_name": "Manning",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109460224256128945/title/5/1-19?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.59509,
        "price": 104950,
        "price_currency": "£",
        "price_formatted": "£104,950",
        "price_high": 104950,
        "price_low": 104950,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "Three bedroom mid town house in need of refurbishment. Situated in ...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/3_bedroom_townhouse_for_sale_109460224256128945.jpg",
        "thumb_width": 80,
        "title": "Western Road, Leeds, West Yorkshire",
        "updated_in_days": 5,
        "updated_in_days_formatted": "first seen 5 days ago"
    },
    {   "id": 19,
        "bathroom_number": "",
        "bedroom_number": 3,
        "car_spaces": 0,
        "commission": 0,
        "construction_year": 0,
        "datasource_name": "OnTheMarket.com",
        "img_height": 300,
        "img_url": "https://imgs.nestimg.com/3_bedroom_semi_detached_house_for_sale_109466411396318205.jpg",
        "img_width": 400,
        "keywords": "Garden, Semi-Detached, No Chain",
        "latitude": 53.8177,
        "lister_name": "Manning",
        "lister_url": "https://www.nestoria.co.uk/detail/0000000109466411396318205/title/5/1-20?serpUid=&pt=1&ot=1&l=leeds&did=105_high1&utm_source=api&utm_medium=external",
        "listing_type": "buy",
        "location_accuracy": 9,
        "longitude": -1.50056,
        "price": 179950,
        "price_currency": "£",
        "price_formatted": "£179,950",
        "price_high": 179950,
        "price_low": 179950,
        "property_type": "house",
        "size": 0,
        "size_type": "net",
        "summary": "Only internal viewing will do full justice to this ly presented thr...",
        "thumb_height": 60,
        "thumb_url": "https://imgs.nestimg.com/medium/3_bedroom_semi_detached_house_for_sale_109466411396318205.jpg",
        "thumb_width": 80,
        "title": "Hetton Road, Leeds - Semi-Detached",
        "updated_in_days": 4,
        "updated_in_days_formatted": "first seen 4 days ago"
    }
];

export default function propertyState(state = initialState) {
    return state;
};

function propList(state, action) {
    if (action.type === "ELEMENTS_LIST") {
        return {...state, proplist: action.payload}
    } else {
        return state
    }
}